name: mems1029-2197-hw01-example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
<<<<<<< HEAD
  - sympy
=======
>>>>>>> b1836ffa79eebc11f789270cc7db90791bb41b03
